/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL2FkbWluL2FkbWluLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL2FkbWluL2FkbWluLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
