/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './not-found.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './not-found.component';
const styles_NotFoundComponent:any[] = [i0.styles];
export const RenderType_NotFoundComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NotFoundComponent,data:{}});
export function View_NotFoundComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  not-found works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_NotFoundComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-not-found',
      ([] as any[]),(null as any),(null as any),(null as any),View_NotFoundComponent_0,
      RenderType_NotFoundComponent)),i1.ɵdid(1,114688,(null as any),0,i2.NotFoundComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NotFoundComponentNgFactory:i1.ComponentFactory<i2.NotFoundComponent> = i1.ɵccf('app-not-found',
    i2.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL25vdC1mb3VuZC9ub3QtZm91bmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0JlbGFqYXJBbmd1bGFyL2F1dGgtZGVtby1zdGFydGVyKDEyKS9hdXRoLWRlbW8vc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0JlbGFqYXJBbmd1bGFyL2F1dGgtZGVtby1zdGFydGVyKDEyKS9hdXRoLWRlbW8vc3JjL2FwcC9ub3QtZm91bmQvbm90LWZvdW5kLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL25vdC1mb3VuZC9ub3QtZm91bmQuY29tcG9uZW50LnRzLk5vdEZvdW5kQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHA+XG4gIG5vdC1mb3VuZCB3b3JrcyFcbjwvcD5cbiIsIjxhcHAtbm90LWZvdW5kPjwvYXBwLW5vdC1mb3VuZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBLCtDQUVDO01BQUE7OztvQkNGSjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
