/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './no-access.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './no-access.component';
const styles_NoAccessComponent:any[] = [i0.styles];
export const RenderType_NoAccessComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_NoAccessComponent,data:{}});
export function View_NoAccessComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted(-1,(null as any),['\n'])),(_l()(),i1.ɵeld(1,0,
      (null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted(-1,(null as any),
      ['Access Denied']))],(null as any),(null as any));
}
export function View_NoAccessComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-no-access',
      ([] as any[]),(null as any),(null as any),(null as any),View_NoAccessComponent_0,
      RenderType_NoAccessComponent)),i1.ɵdid(1,114688,(null as any),0,i2.NoAccessComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const NoAccessComponentNgFactory:i1.ComponentFactory<i2.NoAccessComponent> = i1.ɵccf('app-no-access',
    i2.NoAccessComponent,View_NoAccessComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL25vLWFjY2Vzcy9uby1hY2Nlc3MuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0JlbGFqYXJBbmd1bGFyL2F1dGgtZGVtby1zdGFydGVyKDEyKS9hdXRoLWRlbW8vc3JjL2FwcC9uby1hY2Nlc3Mvbm8tYWNjZXNzLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0JlbGFqYXJBbmd1bGFyL2F1dGgtZGVtby1zdGFydGVyKDEyKS9hdXRoLWRlbW8vc3JjL2FwcC9uby1hY2Nlc3Mvbm8tYWNjZXNzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL25vLWFjY2Vzcy9uby1hY2Nlc3MuY29tcG9uZW50LnRzLk5vQWNjZXNzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG48aDE+QWNjZXNzIERlbmllZDwvaDE+IiwiPGFwcC1uby1hY2Nlc3M+PC9hcHAtbm8tYWNjZXNzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQSwwQ0FDQTtNQUFBO01BQUEsNENBQUk7TUFBQTs7O29CQ0RKO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
