/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './signup.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './signup.component';
const styles_SignupComponent:any[] = [i0.styles];
export const RenderType_SignupComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_SignupComponent,data:{}});
export function View_SignupComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted(-1,(null as any),['\n  signup works!\n'])),(_l()(),i1.ɵted(-1,(null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_SignupComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,0,(null as any),(null as any),1,'app-signup',
      ([] as any[]),(null as any),(null as any),(null as any),View_SignupComponent_0,
      RenderType_SignupComponent)),i1.ɵdid(1,114688,(null as any),0,i2.SignupComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const SignupComponentNgFactory:i1.ComponentFactory<i2.SignupComponent> = i1.ɵccf('app-signup',
    i2.SignupComponent,View_SignupComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL3NpZ251cC9zaWdudXAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0JlbGFqYXJBbmd1bGFyL2F1dGgtZGVtby1zdGFydGVyKDEyKS9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0JlbGFqYXJBbmd1bGFyL2F1dGgtZGVtby1zdGFydGVyKDEyKS9hdXRoLWRlbW8vc3JjL2FwcC9zaWdudXAvc2lnbnVwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQmVsYWphckFuZ3VsYXIvYXV0aC1kZW1vLXN0YXJ0ZXIoMTIpL2F1dGgtZGVtby9zcmMvYXBwL3NpZ251cC9zaWdudXAuY29tcG9uZW50LnRzLlNpZ251cENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICBzaWdudXAgd29ya3MhXG48L3A+XG4iLCI8YXBwLXNpZ251cD48L2FwcC1zaWdudXA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw0Q0FFQztNQUFBOzs7b0JDRko7TUFBQTtnQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
